# Generated by Django 5.2.6 on 2025-10-06 15:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_gasto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraMercaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('numero_factura', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Compra de Mercadería',
                'verbose_name_plural': 'Compras de Mercadería',
            },
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finanzas.compramercaderia')),
            ],
            options={
                'verbose_name': 'Item de Compra',
                'verbose_name_plural': 'Items de Compra',
            },
        ),
        migrations.CreateModel(
            name='PagoSueldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.CharField(max_length=200)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('periodo', models.CharField(help_text='Ej: Enero 2024', max_length=50)),
                ('sueldo_neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aportes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pago de Sueldo',
                'verbose_name_plural': 'Pagos de Sueldos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='RubroGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('FIJO', 'Gasto Fijo'), ('VARIABLE', 'Gasto Variable'), ('EXTRA', 'Gasto Extraordinario')], default='FIJO', max_length=20)),
            ],
            options={
                'verbose_name': 'Rubro de Gasto',
                'verbose_name_plural': 'Rubros de Gastos',
            },
        ),
        migrations.DeleteModel(
            name='Transaccion',
        ),
        migrations.AlterModelOptions(
            name='gasto',
            options={'ordering': ['-fecha'], 'verbose_name_plural': 'Gastos'},
        ),
        migrations.AddField(
            model_name='gasto',
            name='comprobante',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gasto',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='compramercaderia',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.proveedor'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='rubro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='finanzas.rubrogasto'),
            preserve_default=False,
        ),
    ]
