<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-10-06 15:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_compramercaderia_itemcompra_pagosueldo_proveedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Caja Abierta'), ('CERRADA', 'Caja Cerrada')], default='CERRADA', max_length=20)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('egresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Cajas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('comprobante', models.CharField(blank=True, max_length=100)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='finanzas.caja')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='RetiroCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(max_length=200)),
                ('destinatario', models.CharField(max_length=200)),
                ('autorizado_por', models.CharField(blank=True, max_length=200)),
                ('comprobante', models.CharField(blank=True, max_length=100)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiros', to='finanzas.caja')),
            ],
            options={
                'verbose_name': 'Retiro de Caja',
                'verbose_name_plural': 'Retiros de Caja',
                'ordering': ['-fecha'],
            },
        ),
    ]
=======
# Generated by Django 5.2.6 on 2025-10-06 15:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_compramercaderia_itemcompra_pagosueldo_proveedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Caja Abierta'), ('CERRADA', 'Caja Cerrada')], default='CERRADA', max_length=20)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('egresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Cajas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('comprobante', models.CharField(blank=True, max_length=100)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='finanzas.caja')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='RetiroCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(max_length=200)),
                ('destinatario', models.CharField(max_length=200)),
                ('autorizado_por', models.CharField(blank=True, max_length=200)),
                ('comprobante', models.CharField(blank=True, max_length=100)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiros', to='finanzas.caja')),
            ],
            options={
                'verbose_name': 'Retiro de Caja',
                'verbose_name_plural': 'Retiros de Caja',
                'ordering': ['-fecha'],
            },
        ),
    ]
>>>>>>> 221a76dd27c1c9ad53cabb1d52123a32be198d53
