# Generated by Django 5.2.6 on 2025-10-06 15:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_caja_movimientocaja_retirocaja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AddField(
            model_name='proveedor',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='condiciones_garantia',
            field=models.TextField(blank=True, help_text='Términos y condiciones de la garantía'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto_garantias',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cuit',
            field=models.CharField(blank=True, help_text='Formato: 20-12345678-9', max_length=13),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='localidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='notas',
            field=models.TextField(blank=True, help_text='Observaciones internas'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='plazo_garantia',
            field=models.PositiveIntegerField(default=12, help_text='Meses de garantía por defecto'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono_garantias',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_iva',
            field=models.CharField(choices=[('MONOTRIBUTO', 'Monotributista'), ('RESPONSABLE', 'Responsable Inscripto'), ('EXENTO', 'Exento'), ('CONSUMIDOR', 'Consumidor Final')], default='RESPONSABLE', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductoConGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=200)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('fecha_compra', models.DateField()),
                ('fecha_inicio_garantia', models.DateField()),
                ('fecha_fin_garantia', models.DateField()),
                ('meses_garantia', models.PositiveIntegerField(default=12)),
                ('estado_garantia', models.CharField(choices=[('VIGENTE', 'Garantía Vigente'), ('VENCIDA', 'Garantía Vencida'), ('EN_PROCESO', 'En Proceso de Garantía'), ('FINALIZADA', 'Garantía Finalizada')], default='VIGENTE', max_length=20)),
                ('numero_factura', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.compramercaderia')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.proveedor')),
            ],
            options={
                'verbose_name': 'Producto con Garantía',
                'verbose_name_plural': 'Productos con Garantía',
            },
        ),
        migrations.CreateModel(
            name='ReclamoGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reclamo', models.DateField(default=django.utils.timezone.now)),
                ('numero_reclamo', models.CharField(max_length=50, unique=True)),
                ('descripcion_problema', models.TextField()),
                ('sintomas', models.TextField(blank=True, help_text='Qué falla presenta el producto')),
                ('accesorios_entregados', models.TextField(blank=True, help_text='Accesorios que se entregaron con el producto')),
                ('estado', models.CharField(choices=[('INGRESADO', 'Reclamo Ingresado'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Garantía Aprobada'), ('RECHAZADO', 'Garantía Rechazada'), ('REPARADO', 'Producto Reparado'), ('REEMPLAZADO', 'Producto Reemplazado'), ('FINALIZADO', 'Reclamo Finalizado')], default='INGRESADO', max_length=20)),
                ('fecha_ultima_actualizacion', models.DateField(auto_now=True)),
                ('observaciones_proveedor', models.TextField(blank=True)),
                ('solucion_aplicada', models.TextField(blank=True)),
                ('contacto_cliente', models.CharField(blank=True, max_length=100)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.productocongarantia')),
            ],
            options={
                'verbose_name': 'Reclamo de Garantía',
                'verbose_name_plural': 'Reclamos de Garantía',
                'ordering': ['-fecha_reclamo'],
            },
        ),
    ]
