<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-10-06 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_alter_proveedor_options_proveedor_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocongarantia',
            name='fecha_compra',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productocongarantia',
            name='fecha_fin_garantia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productocongarantia',
            name='fecha_inicio_garantia',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reclamogarantia',
            name='numero_reclamo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
=======
# Generated by Django 5.2.6 on 2025-10-06 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_alter_proveedor_options_proveedor_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocongarantia',
            name='fecha_compra',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productocongarantia',
            name='fecha_fin_garantia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productocongarantia',
            name='fecha_inicio_garantia',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reclamogarantia',
            name='numero_reclamo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
>>>>>>> 221a76dd27c1c9ad53cabb1d52123a32be198d53
