# Generated by Django 5.2.6 on 2025-09-30 14:51

import django.db.models.deletion
import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ClaseEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Clase de Equipo')),
            ],
            options={
                'verbose_name': 'Clase de Equipo',
                'verbose_name_plural': 'Clases de Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionDolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_venta', models.DecimalField(decimal_places=2, help_text='Valor del dólar que se usará para calcular precios de venta.', max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cotización del Dólar',
                'verbose_name_plural': 'Cotización del Dólar',
            },
        ),
        migrations.CreateModel(
            name='MarcaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Marca')),
            ],
            options={
                'verbose_name': 'Marca de Equipo',
                'verbose_name_plural': 'Marcas de Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ModeloEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Modelo')),
                ('clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.claseequipo', verbose_name='Clase de Equipo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.marcaequipo', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Modelo de Equipo',
                'verbose_name_plural': 'Modelos de Equipos',
                'ordering': ['clase', 'marca', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('codigo_barras', models.CharField(default=inventario.models.Producto.generar_codigo_barras, max_length=13, unique=True, verbose_name='Código de Barras (EAN-13)')),
                ('precio_venta_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Base (USD)')),
                ('stock_actual', models.PositiveIntegerField(default=0, verbose_name='Stock disponible')),
                ('stock_minimo', models.PositiveIntegerField(default=5, verbose_name='Stock Mínimo de Alerta')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.categoriaproducto', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
