# Generated by Django 5.2.6 on 2025-10-04 20:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizaciondolar',
            options={'verbose_name': 'Cotización del Dólar', 'verbose_name_plural': 'Cotizaciones del Dólar'},
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='categoria_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='inventario.categoriaproducto', verbose_name='Categoría Padre'),
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cotizaciondolar',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cotizaciondolar',
            name='fuente',
            field=models.CharField(default='Manual', help_text='Fuente de la cotización', max_length=100),
        ),
        migrations.AddField(
            model_name='cotizaciondolar',
            name='valor_compra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor de compra del dólar', max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_compra_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Compra (USD)'),
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cotizaciondolar',
            name='valor_venta',
            field=models.DecimalField(decimal_places=2, default=1400.0, help_text='Valor del dólar que se usará para calcular precios de venta.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.categoriaproducto', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Venta (USD)'),
        ),
    ]
