# Generated by Django 5.2.6 on 2025-10-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_cotizaciondolar_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/galeria/')),
                ('orden', models.IntegerField(default=0)),
                ('titulo', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AlterModelOptions(
            name='cotizaciondolar',
            options={'ordering': ['-fecha_actualizacion'], 'verbose_name': 'Cotización del Dólar', 'verbose_name_plural': 'Cotizaciones del Dólar'},
        ),
        migrations.AddField(
            model_name='producto',
            name='caracteristicas',
            field=models.JSONField(blank=True, default=dict, verbose_name='Características Técnicas'),
        ),
        migrations.AddField(
            model_name='producto',
            name='condiciones_garantia',
            field=models.TextField(blank=True, verbose_name='Condiciones de Garantía'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion_larga',
            field=models.TextField(blank=True, verbose_name='Descripción Larga (Web)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_principal',
            field=models.ImageField(blank=True, upload_to='productos/', verbose_name='Imagen Principal'),
        ),
        migrations.AddField(
            model_name='producto',
            name='meses_garantia',
            field=models.PositiveIntegerField(default=0, verbose_name='Meses de Garantía'),
        ),
        migrations.AddField(
            model_name='producto',
            name='meta_descripcion',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='producto',
            name='meta_titulo',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='producto',
            name='orden_destacado',
            field=models.IntegerField(default=0, verbose_name='Orden en Destacados'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor_garantia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Proveedor/Garantía'),
        ),
        migrations.AddField(
            model_name='producto',
            name='publicado_web',
            field=models.BooleanField(default=False, verbose_name='Publicado en Web'),
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tags',
            field=models.CharField(blank=True, help_text='Separar con comas', max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiene_garantia',
            field=models.BooleanField(default=False, verbose_name='Tiene Garantía'),
        ),
        migrations.AddField(
            model_name='producto',
            name='galeria_imagenes',
            field=models.ManyToManyField(blank=True, to='inventario.imagenproducto', verbose_name='Galería de Imágenes'),
        ),
    ]
