# Generated by Django 5.2.6 on 2025-10-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_imagenproducto_alter_cotizaciondolar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Producto Destacado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='margen_ganancia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Margen de Ganancia (%)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Principal'),
        ),
    ]
