# Generated by Django 5.2.6 on 2025-10-09 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_producto_destacado_producto_margen_ganancia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='galeria_imagenes',
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_galeria', to='inventario.producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra_usd',
            field=models.DecimalField(decimal_places=2, help_text='Precio de compra en DÓLARES', max_digits=10, verbose_name='Precio Compra (USD)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta_usd',
            field=models.DecimalField(decimal_places=2, help_text='Precio de venta en DÓLARES', max_digits=10, verbose_name='Precio Venta (USD)'),
        ),
    ]
