# Generated by Django 5.2.6 on 2025-10-09 19:49

import django.db.models.deletion
import django.utils.timezone
import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_itemreparacion_ordentaller_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemReparacion',
        ),
        migrations.DeleteModel(
            name='OrdenTaller',
        ),
        migrations.AlterModelOptions(
            name='imagenproducto',
            options={'ordering': ['orden'], 'verbose_name': 'Imagen de Producto', 'verbose_name_plural': 'Imágenes de Productos'},
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='categoria_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='inventario.categoriaproducto'),
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='slug',
            field=models.SlugField(blank=True, default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cotizaciondolar',
            name='fuente',
            field=models.CharField(default='Manual', max_length=100),
        ),
        migrations.AlterField(
            model_name='cotizaciondolar',
            name='valor_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotizaciondolar',
            name='valor_venta',
            field=models.DecimalField(decimal_places=2, default=1400.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.categoriaproducto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(default=inventario.models.Producto.generar_codigo_barras, max_length=13, unique=True, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Compra (USD)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Venta (USD)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=5, verbose_name='Stock Mínimo'),
        ),
    ]
