<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-09-30 14:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Venta')),
                ('cotizacion_dolar', models.DecimalField(decimal_places=2, default=1405.0, max_digits=10, verbose_name='Cotización del dólar')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total en Pesos')),
                ('estado', models.CharField(choices=[('finalizada', 'Finalizada'), ('anulada', 'Anulada')], default='finalizada', max_length=20, verbose_name='Estado')),
                ('tipo_comprobante', models.CharField(choices=[('A', 'Factura A'), ('B', 'Factura B'), ('C', 'Factura C'), ('T', 'Ticket')], default='C', max_length=1, verbose_name='Tipo de Comprobante')),
                ('comprobante', models.CharField(blank=True, max_length=50, verbose_name='N° Comprobante')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_taller', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario (USD)')),
                ('descuento_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento (USD)')),
                ('subtotal_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal (USD)')),
                ('subtotal_en_pesos', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal (Pesos)')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta_taller', to='inventario.producto', verbose_name='Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas_taller.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
    ]
=======
# Generated by Django 5.2.6 on 2025-09-30 14:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Venta')),
                ('cotizacion_dolar', models.DecimalField(decimal_places=2, default=1405.0, max_digits=10, verbose_name='Cotización del dólar')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total en Pesos')),
                ('estado', models.CharField(choices=[('finalizada', 'Finalizada'), ('anulada', 'Anulada')], default='finalizada', max_length=20, verbose_name='Estado')),
                ('tipo_comprobante', models.CharField(choices=[('A', 'Factura A'), ('B', 'Factura B'), ('C', 'Factura C'), ('T', 'Ticket')], default='C', max_length=1, verbose_name='Tipo de Comprobante')),
                ('comprobante', models.CharField(blank=True, max_length=50, verbose_name='N° Comprobante')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_taller', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario (USD)')),
                ('descuento_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento (USD)')),
                ('subtotal_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal (USD)')),
                ('subtotal_en_pesos', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal (Pesos)')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta_taller', to='inventario.producto', verbose_name='Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas_taller.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
    ]
>>>>>>> 221a76dd27c1c9ad53cabb1d52123a32be198d53
