<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-09-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del negocio')),
                ('cuit', models.CharField(max_length=20, verbose_name='CUIT')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección fiscal')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo del negocio')),
                ('cotizacion_dolar', models.DecimalField(decimal_places=2, default=1405.0, max_digits=10, verbose_name='Cotización del dólar')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Datos del negocio',
            },
        ),
    ]
=======
# Generated by Django 5.2.6 on 2025-09-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del negocio')),
                ('cuit', models.CharField(max_length=20, verbose_name='CUIT')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección fiscal')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo del negocio')),
                ('cotizacion_dolar', models.DecimalField(decimal_places=2, default=1405.0, max_digits=10, verbose_name='Cotización del dólar')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Datos del negocio',
            },
        ),
    ]
>>>>>>> 221a76dd27c1c9ad53cabb1d52123a32be198d53
