<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-09-30 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Campaña')),
                ('asunto', models.CharField(blank=True, help_text='Solo para campañas de Email', max_length=200)),
                ('contenido', models.TextField(verbose_name='Cuerpo del Mensaje')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('segmento_clientes', models.ManyToManyField(blank=True, to='clientes.cliente', verbose_name='Enviar a Clientes')),
            ],
        ),
    ]
=======
# Generated by Django 5.2.6 on 2025-09-30 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Campaña')),
                ('asunto', models.CharField(blank=True, help_text='Solo para campañas de Email', max_length=200)),
                ('contenido', models.TextField(verbose_name='Cuerpo del Mensaje')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('segmento_clientes', models.ManyToManyField(blank=True, to='clientes.cliente', verbose_name='Enviar a Clientes')),
            ],
        ),
    ]
>>>>>>> 221a76dd27c1c9ad53cabb1d52123a32be198d53
