# Generated by Django 5.2.6 on 2025-10-01 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('cliente_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('cliente_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('equipo', models.CharField(max_length=200, verbose_name='Equipo/Marca/Modelo')),
                ('problema', models.TextField(verbose_name='Problema reportado')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico técnico')),
                ('solucion', models.TextField(blank=True, verbose_name='Solución aplicada')),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('diagnostico', 'En Diagnóstico'), ('presupuesto', 'Presupuesto Enviado'), ('espera_repuesto', 'Esperando Repuesto'), ('reparacion', 'En Reparación'), ('completado', 'Completado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='recibido', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_prometida', models.DateField(blank=True, null=True, verbose_name='Fecha prometida')),
                ('presupuesto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Presupuesto')),
                ('costo_final', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo final')),
                ('seña', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Seña')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de Serie')),
                ('accesorios', models.TextField(blank=True, verbose_name='Accesorios que ingresan')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Orden de Taller',
                'verbose_name_plural': 'Órdenes de Taller',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
