# Generated by Django 5.2.6 on 2025-10-01 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Producto/Repuesto')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción/Uso')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='servicios.ordentaller')),
            ],
            options={
                'verbose_name': 'Producto de Reparación',
                'verbose_name_plural': 'Productos de Reparación',
            },
        ),
    ]
