# Generated by Django 5.2.6 on 2025-10-01 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicios', '0002_productoreparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentaller',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordentaller',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email (texto)'),
        ),
        migrations.AlterField(
            model_name='ordentaller',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del Cliente (texto)'),
        ),
        migrations.AlterField(
            model_name='ordentaller',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono (texto)'),
        ),
    ]
