# Generated by Django 5.2.6 on 2025-10-01 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_ordentaller_cliente_alter_ordentaller_cliente_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentaller',
            name='cliente_email',
        ),
        migrations.RemoveField(
            model_name='ordentaller',
            name='cliente_nombre',
        ),
        migrations.RemoveField(
            model_name='ordentaller',
            name='cliente_telefono',
        ),
    ]
