# Generated by Django 5.2.6 on 2025-10-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_remove_ordentaller_cliente_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(default='Mi Taller Técnico', max_length=200, verbose_name='Nombre del Negocio')),
                ('telefono_negocio', models.CharField(default='+5491112345678', max_length=20, verbose_name='Teléfono del Negocio')),
                ('email_negocio', models.EmailField(default='info@mitaller.com', max_length=254, verbose_name='Email del Negocio')),
                ('direccion_negocio', models.TextField(default='Av. Principal 123', verbose_name='Dirección del Negocio')),
                ('logo_negocio', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo del Negocio')),
                ('mensaje_whatsapp', models.TextField(default='¡Hola!  Te damos la bienvenida a nuestro taller. ¿En qué podemos ayudarte?', verbose_name='Mensaje automático de WhatsApp')),
            ],
            options={
                'verbose_name': 'Configuración del Negocio',
                'verbose_name_plural': 'Configuración del Negocio',
            },
        ),
        migrations.AddField(
            model_name='ordentaller',
            name='codigo_consulta',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Código de Consulta'),
        ),
    ]
