# Generated by Django 5.2.6 on 2025-10-01 23:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_configuracionnegocio_ordentaller_codigo_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#3498db', max_length=7, verbose_name='Color (Hex)')),
            ],
            options={
                'verbose_name': 'Categoría de Gasto',
                'verbose_name_plural': 'Categorías de Gastos',
            },
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='dolar_auto',
            field=models.BooleanField(default=True, verbose_name='Actualizar dólar automáticamente'),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='dolar_manual',
            field=models.DecimalField(decimal_places=2, default=985.5, max_digits=10, verbose_name='Dólar Manual'),
        ),
        migrations.AddField(
            model_name='configuracionnegocio',
            name='ultima_actualizacion_dolar',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='configuracionnegocio',
            name='mensaje_whatsapp',
            field=models.TextField(default='¡Hola! 👋 Te damos la bienvenida a nuestro taller. ¿En qué podemos ayudarte?', verbose_name='Mensaje automático de WhatsApp'),
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto del Gasto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('tipo', models.CharField(choices=[('fijo', 'Gasto Fijo'), ('variable', 'Gasto Variable'), ('extraordinario', 'Gasto Extraordinario')], default='variable', max_length=20, verbose_name='Tipo de Gasto')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Gasto')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción Adicional')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.categoriagasto', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10, verbose_name='Tipo')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('relacion_gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.gasto', verbose_name='Relacionado con Gasto')),
                ('relacion_orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.ordentaller', verbose_name='Relacionado con Orden')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
