# Generated by Django 5.2.6 on 2025-10-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_categoriagasto_configuracionnegocio_dolar_auto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='ConfiguracionNegocio',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='relacion_gasto',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='relacion_orden',
        ),
        migrations.AlterField(
            model_name='ordentaller',
            name='codigo_consulta',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Código de Consulta WhatsApp'),
        ),
        migrations.DeleteModel(
            name='CategoriaGasto',
        ),
        migrations.DeleteModel(
            name='Gasto',
        ),
        migrations.DeleteModel(
            name='Transaccion',
        ),
    ]
