# Generated by Django 5.2.6 on 2025-10-07 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_producto_destacado_producto_margen_ganancia_and_more'),
        ('servicios', '0007_remove_gasto_categoria_delete_configuracionnegocio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad usada')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_usados', to='servicios.ordentaller')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto', verbose_name='Producto del Stock')),
            ],
            options={
                'verbose_name': 'Repuesto Usado',
                'verbose_name_plural': 'Repuestos Usados',
            },
        ),
        migrations.DeleteModel(
            name='ProductoReparacion',
        ),
    ]
