<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-09-30 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del equipo')),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('laptop', 'Laptop'), ('pc', 'Computadora de Escritorio'), ('impresora', 'Impresora'), ('monitor', 'Monitor'), ('telefono', 'Telefono'), ('tablet', 'Tablet'), ('otros', 'Otros')], default='laptop', max_length=20)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion adicional')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
=======
# Generated by Django 5.2.6 on 2025-09-30 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del equipo')),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('laptop', 'Laptop'), ('pc', 'Computadora de Escritorio'), ('impresora', 'Impresora'), ('monitor', 'Monitor'), ('telefono', 'Telefono'), ('tablet', 'Tablet'), ('otros', 'Otros')], default='laptop', max_length=20)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion adicional')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
>>>>>>> 221a76dd27c1c9ad53cabb1d52123a32be198d53
