<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-09-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(choices=[('persona', 'Persona Fisica'), ('empresa', 'Empresa')], default='persona', max_length=10, verbose_name='Tipo de cliente')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre o Razon Social')),
                ('apellido', models.CharField(blank=True, max_length=100, verbose_name='Apellido (si es persona)')),
                ('condicion_iva', models.CharField(choices=[('responsable_inscripto', 'Responsable Inscripto'), ('monotributista', 'Monotributista'), ('exento', 'Exento'), ('no_responsable', 'No Responsable'), ('consumidor_final', 'Consumidor Final')], default='consumidor_final', max_length=30, verbose_name='Condicion frente al IVA')),
                ('cuit', models.CharField(blank=True, max_length=13, verbose_name='CUIT/CUIL')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Telefono / WhatsApp')),
                ('domicilio', models.CharField(blank=True, max_length=255, verbose_name='Domicilio')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('provincia', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Notas internas')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
=======
# Generated by Django 5.2.6 on 2025-09-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(choices=[('persona', 'Persona Fisica'), ('empresa', 'Empresa')], default='persona', max_length=10, verbose_name='Tipo de cliente')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre o Razon Social')),
                ('apellido', models.CharField(blank=True, max_length=100, verbose_name='Apellido (si es persona)')),
                ('condicion_iva', models.CharField(choices=[('responsable_inscripto', 'Responsable Inscripto'), ('monotributista', 'Monotributista'), ('exento', 'Exento'), ('no_responsable', 'No Responsable'), ('consumidor_final', 'Consumidor Final')], default='consumidor_final', max_length=30, verbose_name='Condicion frente al IVA')),
                ('cuit', models.CharField(blank=True, max_length=13, verbose_name='CUIT/CUIL')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Telefono / WhatsApp')),
                ('domicilio', models.CharField(blank=True, max_length=255, verbose_name='Domicilio')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('provincia', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Notas internas')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
>>>>>>> 221a76dd27c1c9ad53cabb1d52123a32be198d53
